# Generated by Django 4.2.2 on 2023-08-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='포스트 내용', max_length=300, verbose_name='CONTENT')),
                ('title', models.CharField(default='포스트 제목', max_length=20, verbose_name='TITLE')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='PUB_DATE')),
                ('recommend', models.PositiveIntegerField(default=0, verbose_name='RECOMMEND')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/img/defaultImg.png', upload_to='postImage/', verbose_name='IMAGE')),
                ('post_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noonddockApp.post')),
            ],
        ),
    ]
