# Generated by Django 4.2.2 on 2023-08-13 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noonddockApp', '0004_rename_family_post_user_alter_post_table_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='save',
            old_name='user',
            new_name='family',
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('family', 'post')},
        ),
    ]
