# Generated by Django 4.2.2 on 2023-08-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noonddockApp', '0008_remove_post_like_count_post_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='LIKE_COUNT'),
        ),
    ]
