# Generated by Django 4.2.2 on 2023-08-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noonddockApp', '0010_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default='위치', max_length=300, verbose_name='LOCATION'),
        ),
        migrations.AddField(
            model_name='post',
            name='parking',
            field=models.TextField(default='주차', max_length=300, verbose_name='PARKING'),
        ),
        migrations.AddField(
            model_name='post',
            name='reservation',
            field=models.TextField(default='예약', max_length=300, verbose_name='RESERVATION'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='한줄 눈똑', max_length=300, verbose_name='SUMMARY'),
        ),
    ]
