# Generated by Django 4.2.2 on 2023-08-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noonddockApp', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city_cate',
            field=models.IntegerField(blank=True, null=True, verbose_name='지역'),
        ),
    ]
