# Generated by Django 4.2.2 on 2023-08-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noonddockApp', '0015_post_city_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='포스트 제목', max_length=50, verbose_name='TITLE'),
        ),
    ]
