# Generated by Django 4.2.1 on 2023-08-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='family',
            table='family',
        ),
    ]
