# Generated by Django 4.2.1 on 2023-08-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_family_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='family_name',
            new_name='familyname',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='members_count',
            new_name='members',
        ),
    ]
