# Generated by Django 4.2.1 on 2023-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_rename_family_name_family_familyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='members',
            field=models.IntegerField(null=True),
        ),
    ]
