# Generated by Django 4.2.2 on 2023-08-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
